sudo: required
language: minimal
services:
  - docker

env:
  - secure: "IOwWDncjaWf1CAc8rutSbCeOJFHjIS5DUndvp/xTWNNtfFM/W+1BHhsTGyeA4G/kxXpbne1ob4nWJ16Zi1Km+QCwBplffv5U/trb/dhLZFy9HRBvlpeT9t7Ozh1Oxc2I06mnjL9xoTZC5NpGXwsodN3jZzOD8jgQZYgQ+dnsNXt+fB41b7tEivjM7R7D1zM46dHVFFEiNFyBR+2P4AqgoANCnoFhtjSSxtCcwSBzhlMjYbJc35VU1kt9dRq9cMBySbYicXbMFOrhelj8mDgcOAutFEUykDETCLCtdfA7UopqzYfU44GaQxOYR2E0Y+Nh8em6H8BIMZUAv8kjtPS45YIwroJZ0CvC9nDutasoezB8rCWEDBOaoUgeR8gFWTswrqH0hAD67RJFvMXqIAxvWquITfTvoSWsVMtD6gnE283biict4zW6iAQMNyflXz9dh66SWRg11BQzuk8aia+4/pO4hqlecdAA/nltY2x24MLKbia6Dnfwiri9MZumNTgsAsbdQ84DzbpXV8ZBVFWPczGkkanPCmZVI9Mz7kCJNDoCXn8s1VVc72HReKuOgvHBTX5buOpdF6P33Peha4DSdiSNJt4P8FntdECoc34IxfpTuwpwIfUlkEABxDWXQSLZllkzgO23XU1ZJ+mO+y0OgkmITNDmiYJ8GxhGSSkGDIU="

script:
  - VER=`git log --pretty=tformat:%h -n 1`
  - IMAGE=prcek/k8stestnginx:$VER
  - IMAGE_L=prcek/k8stestnginx:latest
  - echo Image $IMAGE
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $IMAGE .
  - docker tag $IMAGE $IMAGE_L
  - docker push $IMAGE
  - docker push $IMAGE_L
  
