apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: prcek/k8stestnginx:$VER
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 16Mi
    
